# Generated by Django 2.0.2 on 2018-02-10 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('290561bf-9121-47c5-be90-46e0f7f7c000'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db9a0cf3-7e5b-4414-a961-ab7ef6ce8d7e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
